server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "postgres"
  port: 5432
  user: "elotus"
  password: "elotus_password"
  dbname: "elotus_test"
  sslmode: "disable"

jwt:
  secret_key: "changeit"
  expires_in: "24h"

upload:
  max_file_size: 8388608  # 8MB in bytes
  temp_dir: "./files"