services:
  postgres:
    image: postgres:15
    container_name: elotus-test-db
    restart: always
    environment:
      POSTGRES_DB: elotus_test
      POSTGRES_USER: elotus
      POSTGRES_PASSWORD: elotus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup/sql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
        - "3000:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 5 && ./server"]

volumes:
  postgres_data:
